/**
 * This module reexports the services from the @services module,
 * declared in .next/types/interface.d.ts generated by tool/setup-interface.ts.
 *
 * It also checks the complience of the services with the common app interface (Brain).
 */

import { Get, type Paths } from '@lejdar/webdev';
import { Brain } from './interface';

import(`@services`) satisfies Promise<Brain>;
export * from '@services';

export type { Brain };

/**
 * Utility type for implementing a portion of the app interface.
 * Accepts a path key, such as Repository<'product'> or Repository<'product.fetchCategories'>.
 */
export type Repository<Path extends Paths<Brain>> = Get<Brain, Path>;
